# FROM mcr.microsoft.com/devcontainers/base:jammy

FROM sbtscala/scala-sbt:graalvm-community-22.0.0_1.10.0_3.4.2

# install coursier
RUN curl -fL "https://github.com/coursier/launchers/raw/master/cs-x86_64-pc-linux.gz" | gzip -d > cs
RUN chmod +x cs
RUN yes Y | ./cs setup
# RUN cs install bloop --only-prebuilt=true

